In [29]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import numpy as np 

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
dt=load_wine()
print(dir(dt))

print('-'*90+ '\n'*3 + 'next is whole data')
dt


['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']
------------------------------------------------------------------------------------------


next is whole data


{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [30]:

dt_data = dt.data
dt_label = dt.target
print(dt_data.shape)


dt_df = pd.DataFrame(data=dt_data, columns=dt.feature_names)
dt_df["label"] = dt.target

X_train, X_test, y_train, y_test = train_test_split(dt_data, 
                                                    dt_label, 
                                                    test_size=0.2, 
                                                    random_state=7)

(178, 13)


In [31]:
X_train.shape, y_train.shape
X_test.shape, y_test.shape

((36, 13), (36,))

y_pred 는 예측 값 입니다. 
정확도 = 예측 결과가 정답인 데이터의 개수 / 예측한 전체 데이터의 개수

In [32]:
decision_tree = DecisionTreeClassifier(random_state=32)
decision_tree.fit(X_train, y_train)
y_pred = decision_tree.predict(X_test)
y_pred

array([2, 0, 2, 2, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1,
       1, 1, 0, 2, 1, 2, 2, 2, 1, 0, 2, 1, 1, 1])

In [33]:
y_test

array([2, 0, 2, 2, 1, 2, 1, 0, 1, 2, 0, 1, 2, 1, 1, 1, 1, 2, 0, 0, 1, 1,
       1, 1, 0, 2, 1, 2, 2, 2, 1, 0, 2, 1, 1, 1])

In [34]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

accuracy = accuracy_score(y_test, y_pred)
accuracy



0.9444444444444444

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(y_test, y_pred)
array = confusion_matrix(y_test, y_pred) 
total = np.sum(array, axis = 1)
array1 = array / total[:,None]
t1 = array1
array1


array([[1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.16666667, 0.83333333]])

### axis = 1 은 행 단위로 더했다는 뜻입니다.
Confusion matrix 를 보면 decision tree 의 결과는 다음과 같습니다
다음은 random_forest 를 보겠습니다

In [37]:
random_forest = RandomForestClassifier(random_state=32)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)

print(classification_report(y_test, y_pred))



accuracy = accuracy_score(y_test, y_pred)
accuracy
confusion_matrix(y_test, y_pred)
array2 = confusion_matrix(y_test, y_pred) 
total2 = np.sum(array, axis = 1)
array2 = array / total2[:,None]
t2 = array2
array2

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        12

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



array([[1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.16666667, 0.83333333]])

정확도에 있어서 차이가 없습니다.  
confusion_matrix 를 보았을 때 틀린 경우가 없습니다. 좋습니다


In [38]:
from sklearn import svm
import numpy as np
svm_model = svm.SVC()
random_forest = RandomForestClassifier(random_state=32)
svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

print(classification_report(y_test, y_pred))

confusion_matrix(y_test, y_pred) 

array = confusion_matrix(y_test, y_pred) 
total = np.sum(array, axis = 1)
array3 = array / total[:,None]
t3 = array3
array3

              precision    recall  f1-score   support

           0       0.86      0.86      0.86         7
           1       0.58      0.88      0.70        17
           2       0.33      0.08      0.13        12

    accuracy                           0.61        36
   macro avg       0.59      0.61      0.56        36
weighted avg       0.55      0.61      0.54        36



array([[0.85714286, 0.        , 0.14285714],
       [0.05882353, 0.88235294, 0.05882353],
       [0.        , 0.91666667, 0.08333333]])

svm 모델은 조금 차이가 있습니다. 앞서 비교해보았을때 정확도가 훅 떨어집니다. 
2을 주었을 때 1,3 으로 대답한 게 한개씩 있어서 오류가 있습니다.


In [39]:
from sklearn.linear_model import SGDClassifier
sgd_model = SGDClassifier()

print(sgd_model._estimator_type)

random_forest = RandomForestClassifier(random_state=32)
sgd_model.fit(X_train, y_train)
y_pred = sgd_model.predict(X_test)

print(classification_report(y_test, y_pred))
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)
array = confusion_matrix(y_test, y_pred) 
total = np.sum(array, axis = 1)
array4 = array / total[:,None]
t4 = array4
array4

classifier
              precision    recall  f1-score   support

           0       0.37      1.00      0.54         7
           1       0.71      0.71      0.71        17
           2       0.00      0.00      0.00        12

    accuracy                           0.53        36
   macro avg       0.36      0.57      0.41        36
weighted avg       0.40      0.53      0.44        36



/opt/conda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[1.        , 0.        , 0.        ],
       [0.29411765, 0.70588235, 0.        ],
       [0.58333333, 0.41666667, 0.        ]])

### sgd 모델도 정확도가 떨어집니다.
특히 2번(3번째 레이블) 의 정확도가 꽤 떨어집니다. 

In [40]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()

print(logistic_model._estimator_type)

logistic_model.fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)

print(classification_report(y_test, y_pred))
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)
array = confusion_matrix(y_test, y_pred) 
total = np.sum(array, axis = 1)
array5 = array / total[:,None]
t5 = array5
array5

classifier
              precision    recall  f1-score   support

           0       1.00      0.86      0.92         7
           1       0.94      1.00      0.97        17
           2       1.00      1.00      1.00        12

    accuracy                           0.97        36
   macro avg       0.98      0.95      0.96        36
weighted avg       0.97      0.97      0.97        36



/opt/conda/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[0.85714286, 0.14285714, 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ]])

선형회귀 모델이 그나마 앞선 모델들 보다 낫습니다

In [45]:
print('-'*90)
print('decision forest')
print('\n')
print(t1)
print('\n')

x1 = t1.sum(axis = 0)

print(x1)


print('-'*90)
print('random forest')
print('\n')
print(t2)
x2 = t2.sum(axis = 0)
print('\n')
print(x2)

print('-'*90)
print('svm model')
print('\n')
print(t3)
print('\n')
x3 = t3.sum(axis = 0)
print(x3)

print('-'*90)
print('sgd model')
print('\n')
print(t4)
print('\n')
x4 = t4.sum(axis = 0)
print(x4)


print('-'*90)
print('logistic model')
print('\n')
print(t5)
print('\n')
x5 = t5.sum(axis = 0)
print(x5)



------------------------------------------------------------------------------------------
decision forest


[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.16666667 0.83333333]]


[1.         1.16666667 0.83333333]
------------------------------------------------------------------------------------------
random forest


[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.16666667 0.83333333]]


[1.         1.16666667 0.83333333]
------------------------------------------------------------------------------------------
svm model


[[0.85714286 0.         0.14285714]
 [0.05882353 0.88235294 0.05882353]
 [0.         0.91666667 0.08333333]]


[0.91596639 1.79901961 0.28501401]
------------------------------------------------------------------------------------------
sgd model


[[1.         0.         0.        ]
 [0.29411765 0.70588235 0.        ]
 [0.58333333 0.41666667 0.        ]]


[1.87745098 1.12254902 0.    

## axis=0 으로 열 단위로 더하니까 많은 숫자가 나온 열이 문제가 있다는 뜻이 된다.
svm 모델에서는 2열이 즉, 2번째 레이블을 예측할때 많은 실패가 있었다.
행, 렬의 대각 라인만 더하는 함수를 짜고 싶었는데 잘 안되었다
결과를 이렇게 한번에 보니까 svm 모델이 문제가 꽤 많다.

SVM은 분류에 사용되는 지도학습 머신러닝 모델이다.
SVM은 서포트 벡터(support vectors)를 사용해서 결정 경계(Decision Boundary)를 정의하고, 분류되지 않은 점을 해당 결정 경계와 비교해서 분류한다.
서포트 벡터(support vectors)는 결정 경계에 가장 가까운 각 클래스의 점들이다.
