In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

dt=load_breast_cancer()
print(dir(dt))

print('-'*90+ '\n'*3 + 'next is whole data')
dt


['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']
------------------------------------------------------------------------------------------


next is whole data


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

target 은 정답지 입니다

## 이렇게 데이터를 다 보는 것도 중요한 것 같습니다.


In [3]:

dt_data = dt.data
dt_label = dt.target
print(dt_data.shape)


dt_df = pd.DataFrame(data=dt_data, columns=dt.feature_names)
dt_df["label"] = dt.target

X_train, X_test, y_train, y_test = train_test_split(dt_data, 
                                                    dt_label, 
                                                    test_size=0.2, 
                                                    random_state=7)


(569, 30)


### dt.target_name 으로 하면 오류가 뜹니다
따라서 dt.target 으로 적어주어야 합니다
스트링보다는 0,1이 편한 것 같아요!

In [4]:
X_train.shape, y_train.shape
X_test.shape, y_test.shape

((114, 30), (114,))

In [5]:
decision_tree = DecisionTreeClassifier(random_state=32)
decision_tree.fit(X_train, y_train)
y_pred = decision_tree.predict(X_test)
y_pred

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1])

In [6]:
y_test

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1])

In [7]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

accuracy = accuracy_score(y_test, y_pred)
accuracy


0.9122807017543859

In [8]:
from sklearn.metrics import confusion_matrix
import numpy as np
X_train, X_test, y_train, y_test = train_test_split(dt_data, 
                                                    dt_label, 
                                                    test_size=0.2, 
                                                    random_state=7)
confusion_matrix(y_test, y_pred)
array = confusion_matrix(y_test, y_pred) 
total = np.sum(array, axis = 1)
array1 = array / total[:,None]
t1 = array1
array1

print('-'*90)
a2 = 0
print('-'*90)
for value1 in range(2,-2,-1):
    d2 = np.diag(array1,k= value1)
    a2 = a2 + np.sum(d2)
print(a2)

d29 = np.sum(np.diag(array1,k=0))
print(a2-d29)
e2 = a2 - d29
print("제가 만든 성능지표는 : ")
print(e2/a2)

------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
2.0
0.21554054054054061
제가 만든 성능지표는 : 
0.10777027027027031


In [9]:
random_forest = RandomForestClassifier(random_state=32)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)

print(classification_report(y_test, y_pred))



accuracy = accuracy_score(y_test, y_pred)
accuracy
confusion_matrix(y_test, y_pred)
array2 = confusion_matrix(y_test, y_pred) 
total2 = np.sum(array, axis = 1)
array2 = array / total2[:,None]
t2 = array2
array2

print('-'*90)
a3 = 0
print('-'*90)
for value1 in range(2,-2,-1):
    d2 = np.diag(array2,k= value1)
    a3 = a3 + np.sum(d2)
print(a3)

d30 = np.sum(np.diag(array2,k=0))
print(a3-d30)
e3 = a3 - d30
print("제가 만든 성능지표는 : ")
print(e3/a3)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      1.00      1.00        74

    accuracy                           1.00       114
   macro avg       1.00      1.00      1.00       114
weighted avg       1.00      1.00      1.00       114

------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
2.0
0.21554054054054061
제가 만든 성능지표는 : 
0.10777027027027031


In [10]:
from sklearn import svm
import numpy as np
svm_model = svm.SVC()
random_forest = RandomForestClassifier(random_state=32)
svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

print(classification_report(y_test, y_pred))

confusion_matrix(y_test, y_pred) 

array = confusion_matrix(y_test, y_pred) 
total = np.sum(array, axis = 1)
array3 = array / total[:,None]
t3 = array3
array3
print('-'*90)
a4 = 0
print('-'*90)
for value1 in range(2,-2,-1):
    d3 = np.diag(array3,k= value1)
    a4 = a4 + np.sum(d3)
print(a4)

d31 = np.sum(np.diag(array3,k=0))
print(a4-d31)
e4 = a4 - d31
print("제가 만든 성능지표는 : ")
print(e4/a4)

              precision    recall  f1-score   support

           0       1.00      0.72      0.84        40
           1       0.87      1.00      0.93        74

    accuracy                           0.90       114
   macro avg       0.94      0.86      0.89       114
weighted avg       0.92      0.90      0.90       114

------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
2.0
0.2749999999999999
제가 만든 성능지표는 : 
0.13749999999999996


In [12]:
from sklearn.linear_model import SGDClassifier
sgd_model = SGDClassifier()

print(sgd_model._estimator_type)

random_forest = RandomForestClassifier(random_state=32)
sgd_model.fit(X_train, y_train)
y_pred = sgd_model.predict(X_test)

print(classification_report(y_test, y_pred))
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)
array = confusion_matrix(y_test, y_pred) 
total = np.sum(array, axis = 1)
array4 = array / total[:,None]
t4 = array4
array4

print('-'*90)
sum4 = 0
for i in range(array4.shape[0]):
    for j in range (array4.shape[1]):
        if j != i:
            sum4 = sum4 + array[i][j]
print(sum4)

det4 = np.linalg.det(array4)

print (det4) # 대각라인에 있는 걸 다 곱함(determinant)

print('-'*90)
a5 = 0
print('-'*90)
for value1 in range(2,-2,-1):
    d4 = np.diag(array4,k= value1)
    a5 = a5 + np.sum(d4)
print(a5)

d32 = np.sum(np.diag(array4,k=0))
print(a5 - d32)
e5 = a5 - d32
print("제가 만든 성능지표는 : ")
print(e5/a5)

classifier
              precision    recall  f1-score   support

           0       0.83      0.85      0.84        40
           1       0.92      0.91      0.91        74

    accuracy                           0.89       114
   macro avg       0.87      0.88      0.88       114
weighted avg       0.89      0.89      0.89       114

------------------------------------------------------------------------------------------
13
0.7554054054054054
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
1.9999999999999998
0.24459459459459443
제가 만든 성능지표는 : 
0.12229729729729723


In [13]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()

print(logistic_model._estimator_type)

logistic_model.fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)

print(classification_report(y_test, y_pred))
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)
array = confusion_matrix(y_test, y_pred) 
total = np.sum(array, axis = 1)
array5 = array / total[:,None]
t5 = array5
array5

print('-'*90)
a6 = 0
print('-'*90)
for value1 in range(2,-2,-1):
    d5 = np.diag(array5,k= value1)
    a6 = a6 + np.sum(d5)
print(a4)

d33 = np.sum(np.diag(array5,k=0))
print(a6-d33)
e6 = a6 - d33
print("제가 만든 성능지표는 : ")
print(e6/a6)

classifier
              precision    recall  f1-score   support

           0       1.00      0.85      0.92        40
           1       0.93      1.00      0.96        74

    accuracy                           0.95       114
   macro avg       0.96      0.93      0.94       114
weighted avg       0.95      0.95      0.95       114

------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
2.0
0.1499999999999999
제가 만든 성능지표는 : 
0.07499999999999996


/opt/conda/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
print('-'*90)
print('decision forest')
print('\n')
print(t1)
print('\n')

print('-'*90)
print('random forest')
print('\n')
print(t2)
print('\n')

print('-'*90)
print('svm model')
print('\n')
print(t3)
print('\n')

print('-'*90)
print('sgd model')
print('\n')
print(t4)
print('\n')

print('-'*90)
print('logistic model')
print('\n')
print(t5)

------------------------------------------------------------------------------------------
decision forest


[[0.825      0.175     ]
 [0.04054054 0.95945946]]


------------------------------------------------------------------------------------------
random forest


[[0.825      0.175     ]
 [0.04054054 0.95945946]]


------------------------------------------------------------------------------------------
svm model


[[0.725 0.275]
 [0.    1.   ]]


------------------------------------------------------------------------------------------
sgd model


[[0.85       0.15      ]
 [0.09459459 0.90540541]]


------------------------------------------------------------------------------------------
logistic model


[[0.85 0.15]
 [0.   1.  ]]


FP 가 적어야 하므로, (1,0)이 적어야 합니다 따라서 svm , logistic model 이 적합함을 알 수 있었습니다. 

In [15]:
e = [e2,e3,e4,e5,e6]
a = [a2,a3,a4,a5,a6]

for x in range (5):
    print(e[x]/a[x])

0.10777027027027031
0.10777027027027031
0.13749999999999996
0.12229729729729723
0.07499999999999996


#1등은 logistic model 이고 공동2등은 의사결정나무입니다. 꼴등은 svm모델입니다 의외이군요 다른 데이터셋에서는 높은 점수를 받았습니다.  